# Generated by Django 4.2.1 on 2023-05-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('water_needs', models.CharField(max_length=100)),
                ('sun_needs', models.CharField(max_length=100)),
            ],
        ),
    ]
