# Generated by Django 4.2.1 on 2023-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plant_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fertilizer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun_needs',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('B', 'Bright')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_needs',
            field=models.CharField(choices=[('L', 'Low (drought tolerant)'), ('M', 'Moderate (every 1-2 weeks)'), ('H', 'High (2-3 times a week)')], default='M', max_length=1),
        ),
    ]
