# Generated by Django 4.2.1 on 2023-05-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watering_alter_plant_sun_needs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watering',
        ),
    ]
