# Generated by Django 4.2.1 on 2023-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_watering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watering',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_needs',
            field=models.CharField(choices=[('L', 'Low (every 2 weeks)'), ('M', 'Moderate (every week)'), ('H', 'High (2 times a week)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(verbose_name='Watering date'),
        ),
    ]
