# Generated by Django 4.2.1 on 2023-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_pot_delete_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.pot'),
        ),
    ]
