# Generated by Django 4.2.1 on 2023-05-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_plant_pots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='still alive?'),
        ),
    ]
