# Generated by Django 4.2.1 on 2023-06-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_plant_alive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pot',
            new_name='Soil',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='pots',
            new_name='soils',
        ),
    ]
