# Generated by Django 4.2.1 on 2023-06-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_pot_soil_rename_pots_plant_soils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='color',
        ),
        migrations.RemoveField(
            model_name='soil',
            name='size',
        ),
        migrations.AddField(
            model_name='soil',
            name='mixture',
            field=models.CharField(default='Perlite', max_length=100, verbose_name='soil composition and additives'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soil',
            name='type',
            field=models.CharField(choices=[('I', 'Indoor'), ('O', 'Outdoor/Garden')], default='I', max_length=1, verbose_name='Soil Mixture Type'),
        ),
    ]
