# Generated by Django 4.2.1 on 2023-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_soil_color_remove_soil_size_soil_mixture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_needs',
            field=models.CharField(choices=[('I', 'Infrequent'), ('R', 'Regular'), ('F', 'Frequent')], default='R', max_length=1),
        ),
    ]
