# Generated by Django 4.2.1 on 2023-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_plant_water_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sun_needs',
            field=models.CharField(choices=[('L', 'low'), ('M', 'moderate'), ('B', 'bright')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_needs',
            field=models.CharField(choices=[('I', 'infrequent'), ('R', 'regular'), ('F', 'frequent')], default='R', max_length=1, verbose_name='Watering Needs'),
        ),
    ]
