# Generated by Django 4.2.1 on 2023-06-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0016_alter_plant_sun_needs_alter_plant_water_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='Still Alive?'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='mixture',
            field=models.CharField(max_length=100, verbose_name='Soil Composition and Additives'),
        ),
    ]
