# Generated by Django 4.2.1 on 2023-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_plant_user_alter_plant_alive_alter_soil_mixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='type',
        ),
        migrations.AddField(
            model_name='plant',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='S', max_length=1),
        ),
    ]
