# Generated by Django 4.2.1 on 2023-06-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_plant_type_plant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='type',
            field=models.CharField(choices=[('I', 'Indoor'), ('O', 'Outdoor')], default='I', max_length=1, verbose_name='Soil Mixture Type'),
        ),
    ]
